name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependencias 1
        run: pip install telebot
        
      - name: Instalar dependencias 2
        run: pip install requests
        
      - name: Instalar dependencias 3
        run: pip install sys
        
      - name: Instalar dependencias 4
        run: pip install pytest
        
      - name: Run unit tests
        run: python RubenJorge_DO_bot/test.py

      - name: Run dynamic tests
        run: python RubenJorge_DO_bot/test-main.py
